backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: re-couture
    label: Re-Couture
    folder: src/pages/re-couture
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: project-detail,
        }
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options: ['collections', 'collaborations', 'exhibitions']
      - { name: title, label: Title }
      - {
          name: headerImage,
          label: Header image,
          widget: object,
          fields:
            [
              { label: file, name: image, widget: image },
              {
                label: alternative text description,
                name: alt,
                widget: string,
              },
            ],
        }
      - { name: description, label: Project description, widget: text }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: file, name: image, widget: image }
          - { label: alternative text description, name: alt, widget: string }

  - name: re-space
    label: Re-Space
    folder: src/pages/re-space
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: Template Key,
          name: templateKey,
          widget: hidden,
          default: project-detail,
        }
      - { name: title, label: Title }
      - {
          name: headerImage,
          label: Header image,
          widget: object,
          fields:
            [
              { label: file, name: image, widget: image },
              {
                label: alternative text description,
                name: alt,
                widget: string,
              },
            ],
        }
      - { name: description, label: Project description, widget: text }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: file, name: image, widget: image }
          - { label: alternative text description, name: alt, widget: string }
